### ISSUE TITLE
7. testing

### ISSUE THREAD

**Issue by CYCBrian** [CYCBrian/wk13-ORM-E-commerce-Back-End#13]
finally time to connect, create db, seed the stuff, and test if the get, post, put, and delete routes in all the files work.

**Comment by CYCBrian** [comment]
Testing is ongoing, but so far I've tested get request and it works.

Fixed a issue where reference tables were not found. Apparently modelName in all the files are not capitalize, so now all the model names are capitalized and it works now.

for example in the Category.js. modelName used to be 'category', now it is 'Category'.

this was the error
`Unhandled rejection SequelizeDatabaseError: Failed to open the referenced table 'category'
    at Query.formatError (D:\WEBDEV\Modules\13-orm\wk13-ORM-E-commerce-Back-End\develop\node_modules\sequelize\lib\dialects\mysql\query.js:244:16)
    at Query.handler [as onResult] (D:\WEBDEV\Modules\13-orm\wk13-ORM-E-commerce-Back-End\develop\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Query.execute (D:\WEBDEV\Modules\13-orm\wk13-ORM-E-commerce-Back-End\develop\node_modules\mysql2\lib\commands\command.js:36:14)
    at Connection.handlePacket (D:\WEBDEV\Modules\13-orm\wk13-ORM-E-commerce-Back-End\develop\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\WEBDEV\Modules\13-orm\wk13-ORM-E-commerce-Back-End\develop\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\WEBDEV\Modules\13-orm\wk13-ORM-E-commerce-Back-End\develop\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\WEBDEV\Modules\13-orm\wk13-ORM-E-commerce-Back-End\develop\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by CYCBrian** [comment]
Keep getting SequelizeEagerLoadingError only in product-routes.
CRUD functions in category-routes and tag-routes

**Comment by CYCBrian** [comment]
Testing completed. All issues resolved. I was initially unable to create a new product. But I realize I was using tag_id for all my codes, while the starter code was using tagId. Once I changed that in my post request for product I was able to get everything working.
